name: "GreetContributor"
on:
  pull_request:
    types: [opened,synchronize]
    
jobs:
  GreetCommitter: 
    runs-on: ubuntu-latest
    steps:
    - name: "Greet contributor"
      uses: AyushSarode/Social-media-buttons.github.io
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
